name: Update Zen Quote

on:
  schedule:
    - cron: '*/5 * * * *' # This runs the action every 5 minutes
  workflow_dispatch: # This allows manual triggering of the action

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install axios # Install axios to make API requests

      - name: Get a new quote from Zen API
        run: |
          node -e "
          const axios = require('axios');
          const fs = require('fs');
          const filePath = 'daily_snippets.txt';

          async function fetchQuote() {
            try {
              const response = await axios.get('https://zenquotes.io/api/random');
              const quote = response.data[0].q;
              const author = response.data[0].a;
              const timestamp = new Date().toISOString();

              const newQuote = \`\${timestamp}: '\${quote}' - \${author}\n\`;

              fs.appendFileSync(filePath, newQuote);
              console.log('Quote added successfully');
            } catch (error) {
              console.error('Error fetching quote:', error);
            }
          }

          fetchQuote();
          "

      - name: Commit and push quote
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}
          git add daily_snippets.txt
          git commit -m "Update quote: $(date)" || echo "No changes to commit"
          git push origin main
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
